---
abstract: 'Perl 5 bindings to FFmpeg/lib(av(codec|format|util|filter|device)|sw(resample|scale)) via Inline::C and Inline::Module.'
author:
  - 'Ian P Bradley <ian@hikki.tech>'
build_requires: {}
configure_requires:
  Const::Fast: '0'
  Data::Printer: '0'
  File::chdir: '0'
  Future::AsyncAwait: '0'
  Getopt::Long: '0'
  HTTP::Tinyish: '0'
  IO::Async: '0'
  IO::Async::SSL: '0'
  IO::Socket::SSL: '0'
  IPC::Run3: '0'
  Inline: '0'
  Inline::C: '0'
  Inline::CPP: '0'
  Inline::Module: '0'
  InlineX::C2XS: '0'
  JSON::MaybeXS: '0'
  List::AllUtils: '0'
  Module::Build: '0.42'
  Module::Build::InlineModule: '0'
  Net::SSLeay: '0'
  Object::Pad: '0'
  Path::Tiny: '0'
  Pod::Usage: '0'
  Struct::Dumb: '0'
  Syntax::Keyword::Defer: '0'
  Syntax::Keyword::Dynamically: '0'
  Syntax::Keyword::MultiSub: '0'
  Syntax::Keyword::Try: '0'
  TOML::Tiny: '0'
  Time::HiRes: '0'
  perl: v5.40.0
dynamic_config: 1
generated_by: 'Module::Build version 0.4234, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: FFmpeg::Inline
provides:
  FFmpeg::Inline:
    file: lib/FFmpeg/Inline.pm
    version: '0.01'
  FFmpeg::Inline::Stub:
    file: lib/FFmpeg/Inline/Stub.pm
requires:
  Inline::Module: '0'
  Object::Pad: '0'
  Path::Tiny: '0'
  Pod::Usage: '0'
  Syntax::Keyword::Try: '0'
  TOML::Tiny: '0'
  Test::More: '0'
  Time::HiRes: '0'
resources:
  license: http://dev.perl.org/licenses/
version: '0.01'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
